name:  Deploy

on:
push:
  branches: [main]

jobs:

  build:
      name: Post Build
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
            key: ${{secrets.SSH_KEY}} # Private or public key of the server
            username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

            script: |
            
<<<<<<< HEAD
             
              git clone https://ambalisachin:${{secrets.GITHUB_TOKEN}}@github.com/ambalisachin/go-todo.git
=======
              export GO_DIR=/usr/local/go
              source /usr/local/go/bin/go

              cd /root
              cd go
              cd deploying

              echo "Cloning Git Repo to /root/deploying"
              git clone https://ambalisachin:${{secrets.GIT_TOKEN}}@github.com/ambalisachin/go-todo.git
>>>>>>> 9d7319c55942bb57c853b0bbc54d761faebaa4b4

              echo "Building Golang source"
              cd go-todo
              go build

